"""Порт хранилища диалогов."""
from typing import Protocol

from .model import Chat


class ChatRepository(Protocol):
    def ensure(self, chat: Chat) -> Chat: ...
    def update(self, chat: Chat) -> Chat: ...
    def append_message(self, chat: Chat, message: dict) -> Chat: ...
    def get(self, chat_id: str) -> Chat: ...
    def list(self) -> list[dict]: ...
    def delete(self, chat_id: str) -> None: ...
